[{"app_id": "org.jupyter.JupyterLab", "date_created": 1684732501.0, "description": "No problem so far and works well.", "distro": "Fedora Linux", "karma_down": 0, "karma_up": 4, "locale": "en_US.UTF-8", "rating": 100, "reported": 0, "review_id": 591203, "score": 21, "summary": "Works well", "user_display": "Maxime Landry", "version": "4.0.0"}, {"app_id": "org.jupyter.JupyterLab", "date_created": 1691108824.0, "description": "perfect, work well", "distro": "AlmaLinux", "karma_down": 0, "karma_up": 0, "locale": "en_US.UTF-8", "rating": 100, "reported": 0, "review_id": 598144, "score": 0, "summary": "perfect", "user_display": "suriane", "version": "4.0.2"}]